package sembako.sayunara.android.ui.component.splashcreen.model;

public class AppColor {
	public String app_name;
	public String bg_login;
	public String bg_activity;
	public String bg_splashscreen;
	public String bg_toolbar_main;
	public String bg_toolbar_detail;
	public String bg_header_app;
	public String bg_accent;
	public String text_headtittle;
	public String login_logo;
	public String splash_logo;
	public String cover_katam;
	public String header_logo;
	public double app_version;
	public boolean menu_timeline;
	public boolean menu_home;
	public boolean menu_profile;
	public boolean menu_article;
	public boolean menu_events;
	public boolean menu_forums;
	public boolean menu_question;
	public boolean menu_survey;
	public boolean menu_store;
	public boolean menu_harvest;
	public boolean menu_management;
	public boolean menu_fertilizer;
	public boolean menu_pendanaan;
	public boolean menu_video;
	public boolean menu_rank;
	public boolean menu_perairan;
	public boolean menu_prakiraan;
	public boolean menu_sms;
	public boolean menu_weather;
	public boolean menu_price;
	public boolean post_question;
	public boolean post_store;
	public boolean post_harvest;
	public boolean post_fertilizer;
	public boolean post_tangkap;
	public boolean required_login;
	public boolean required_update;
	public boolean menu_akses_keuangan;
	public boolean menu_topup;
	public boolean menu_agen46;
	public boolean post_jual_hasil_pertanian;
	public boolean post_beli_hasil_pertanian;
	public boolean post_articles;

}
